myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<str:category_slug>', views.product_list, name='product_list_by_category'),
    path('<int:id>/<str:slug>', views.product_details, name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200,db_index=True,unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return "%s"%(self.name)

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=True)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('created',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return "%s"%(self.name)
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Product

# Create your views here.

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,'shop/products/list.html', {
        'category': category,
        'categories': categories,
        'products': products
    })

def product_details(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)

    return render(request,
                  'shop/products/detail.html',
                  {'product': product})

shop/templates/shop/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Online Shop </title>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<script src="https://ajax.googleapis.com/ajaz/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'shop/style.css' %}"/>
</head>
<body  style="background-color: lavender;;border:5px solid lawngreen">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!--logo-->
            <div style="font-weight: bold;font-size: 40px" class="navbar-header">
                <a href="/" class="logo">Poor Man Shop </a>
            </div>

            <!--menu items-->

            <!---right aligh-->
            <ul class="nav navbar-nav navbar-right">
                <li>

                    <div style="position:relative;right: 50px;top:40px">
                        {% with total_items=cart|length %}
                            {% if cart|length > 0 %}
                                Your cart:
                                <a href="#">

                                </a>
                            {% else %}
                                 Your cart is empty.
                             {% endif %}
                         {% endwith %}
                     </div>
                </li>
            </ul>
        </div>
    </nav>

    <div style="padding:0 100px;overflow:hidden;position: relative;top:0px"class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

shop/templates/shop/products/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <div class="product-detail">
        <img style="width: 250px" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "shop/no_image.png" %}{% endif %}"height="300"">
        <h1>{{ product.name }}</h1>
        <h2><a href="/"> Back </a></h2>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }} </a></h2>
        <p class="price">Tk:{{ product.price }}</p>
        <form action="#" method="post">

            {% csrf_token %}
            <input type="submit" value="Add to cart">
        </form>
        {{ product.description|linebreaks }}
    </div>
{% endblock %}

shop/templates/shop/products/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
    <div id="sidebar">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}">All</a>
            </li>
        {% for c in categories %}
            <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            </li>
        {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
        {% for product in products %}
            <div class="item">
                <a href="#">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "shop/Netural.jpg" %}{% endif %}"height="200">
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                Tk:{{ product.price }}
            </div>
        {% endfor %}
    </div>
{% endblock %}